#!/usr/bin/env ruby

require 'json'
require 'ostruct'
require 'awesome_print'

def read_json(file_name)
  JSON.parse(File.read(file_name), object_class: OpenStruct)
end

def hash_affordances(o)
  affs = o.affordances.map { |a| [(a.http_method || "GET"), a.return_type] }
  affordances_by_name = Hash[o.affordances.map(&:name).zip(affs)]
  hash = { "#{o.representation_uuid}": affordances_by_name }
end

def print_affordances(o)
  affordances_by_name = Hash[o.affordances.map(&:name).
                               zip(o.affordances.map(&:return_type))]
  hash = { "#{o.representation_uuid}": affordances_by_name }
  puts "#{o.representation_uuid.split('#').first} affordances:"
  ap hash
end

require 'active_support/inflector'
require 'thor'

DELIMITER = '#'
class Pica < Thor
  # NOTE: "special" means their name is generic and
  # thus we need to peek at the input/output rather
  # than rely on the link relation to specify
  SPECIAL_RESOURCES = ["self", "up", "root"]
  attr_accessor :app_name
  include Thor::Actions

  desc "g <directory of representations> <optional: app name>",
       "generates Sinatra app, uses default file name for app name if none given"
  option :force, :type => :boolean

  def self.source_root
    File.dirname(__FILE__)
  end

  def g(representations_dir, app_name = "ExamplePicaApp")
    @app_name = app_name
    resources = create_resources(representations_dir)
    create_app(routes_from(resources))
    create_rack_file
  end

  private
  def create_resources(representations_dir)
    resources = []
    link_relations = []
    Dir.glob("#{representations_dir}/*.json") do |json_file|
      json = read_json(json_file)
      print_affordances(json)
      link_relations << hash_affordances(json)
      resources << json["affordances"]
    end

    @link_relations = []
    link_relations.each do |e|
      e.values.first.each_pair do |k, v|
        next if ['self', 'root'].include?(link_relation = k.split(DELIMITER).first)

        @link_relations << OpenStruct.new(
          {
            input: e.keys.first.to_s.split(DELIMITER).first,
            output: v[1].split(DELIMITER).first,
            direction: (v[0] === 'GET' ? 'none' : ''),
            label: link_relation
          }
        )
      end
    end
    template('templates/dot.erb', "#{app_name}/#{app_name}.dot")

    resources.flatten.each do |r|
      @representation = r
      if SPECIAL_RESOURCES.include?(r.name)
        name = r.return_type.split(DELIMITER).first
        @representation.name = name
      end

      template(
        'templates/resource.erb',
        "#{app_name}/resources/#{@representation.name}.rb"
      )
    end

    resources.compact.flatten
  end

  def routes_from(resources)
    routes = resources.map do |r|
      OpenStruct.new(
        {
          file_name: "./resources/#{r.name}.rb",
          class_name: "#{r.name.classify}"
        }
      )
    end
    routes.compact.uniq
  end

  def create_app(routes)
    @routes = routes
    template('templates/app.erb', "#{app_name}/#{app_name}.rb")
  end

  def create_rack_file
    template('templates/rackup.erb', "#{app_name}/config.ru")
  end
end

Pica.start
