#!/usr/bin/env ruby

require 'json'
require 'ostruct'
require 'awesome_print'

def read_json(file_name)
  JSON.parse(File.read(file_name), object_class: OpenStruct)
end

def hash_affordances(o)
  { "#{o.representation_uuid}": Hash[o.affordances.map(&:name).zip(o.affordances.map(&:return_type))] }
end

def print_affordances(o)
  hash = hash_affordances(o)
  puts "#{o.representation_uuid.split(':').first} affordances:"
  ap hash
end

tiger = read_json('./examples/zoo/representations/tiger.json')
print_affordances(tiger)

animals = read_json('./examples/zoo/representations/animals.json')
print_affordances(animals)
